---
deployment:
  tasks:
    - export PATH1=/home3/snweba2e/public_html/leadsflow.snwebkarma.in/
    - export PATH2=/home3/snweba2e/leadsflow.snwebkarma.in/
    - /bin/mkdir -p $PATH1
    - /bin/mkdir -p $PATH2
    - /bin/cp -r . $PATH1
    - /bin/cp -r . $PATH2
